markdown:         rdiscount
pygments:         true
paginate:         4

title:            Yelaws
url:              http://www.yelaws.com
feed:             /atom.xml
author:
    name:         Yelaws
    email:        yelaws@vip.qq.com
    description:  ""

about:            "我叫叶云峰"
follow:
    email:        yelaws@vip.qq.com
    #github:       https://github.com/pizn
    #twitter:      http://www.twitter.com/piznlin
    #google:       https://plus.google.com/107483619032085919305
    #facebook:     http://facebook.com/zhanxinlin
    weibo:	
description:      

indexContent:     true
imageLink:        http://www.yelaws.com


style:            /css/style.css
blogName:         Yelaws
blogDesc:         I'm a lawer.
favicon:          /favicon.ico
theme:            blue

#disqus:           piznblog

copyright:        Copyright © 2011-2012 Yelaws All rights reserved.
#test:             ok
encoding:	UTF-8